# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 20:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='workflowversion',
            options={'ordering': ['created']},
        ),
    ]
