# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('N', 'New'), ('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running'), ('O', 'Store Job Output'), ('T', 'Terminate VM'), ('F', 'Finished'), ('E', 'Errored'), ('C', 'Canceled')], default='N', max_length=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vm_flavor', models.CharField(default='m1.small', max_length=255)),
                ('vm_instance_name', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging', models.CharField(choices=[('I', 'Input'), ('P', 'Param'), ('O', 'Output')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('dds_file', 'Duke DS File'), ('dds_file_array', 'Duke DS File Array'), ('url_file', 'File URL')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='data.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobParamDDSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('path', models.TextField(null=True)),
                ('dds_app_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DDSApplicationCredential')),
                ('dds_user_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DDSUserCredential')),
                ('job_param', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dds_file', to='data.JobParam')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='data.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='workflow_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.WorkflowVersion'),
        ),
    ]
