# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161201_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDSJobInputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('destination_path', models.CharField(max_length=255, null=True)),
                ('index', models.IntegerField(null=True)),
                ('dds_app_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DDSApplicationCredential')),
                ('dds_user_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DDSUserCredential')),
            ],
        ),
        migrations.CreateModel(
            name='JobInputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('dds_file', 'DukeDS File'), ('dds_file_array', 'DukeDS File Array'), ('url_file', 'URL File'), ('url_file_array', 'URL File Array')], max_length=30)),
                ('workflow_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOutputDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=255, null=True)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('dds_app_credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DDSApplicationCredential')),
                ('dds_user_credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DDSUserCredential')),
            ],
        ),
        migrations.CreateModel(
            name='URLJobInputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('destination_path', models.CharField(max_length=255, null=True)),
                ('index', models.IntegerField(null=True)),
                ('job_input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_files', to='data.JobInputFile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ddsresource',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ddsresource',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='jobparam',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobparamddsfile',
            name='dds_app_credentials',
        ),
        migrations.RemoveField(
            model_name='jobparamddsfile',
            name='dds_user_credentials',
        ),
        migrations.RemoveField(
            model_name='jobparamddsfile',
            name='job_param',
        ),
        migrations.AddField(
            model_name='job',
            name='workflow_input_json',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='DDSResource',
        ),
        migrations.DeleteModel(
            name='JobParam',
        ),
        migrations.DeleteModel(
            name='JobParamDDSFile',
        ),
        migrations.AddField(
            model_name='joboutputdir',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_dir', to='data.Job'),
        ),
        migrations.AddField(
            model_name='jobinputfile',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='data.Job'),
        ),
        migrations.AddField(
            model_name='ddsjobinputfile',
            name='job_input_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dds_files', to='data.JobInputFile'),
        ),
    ]
