# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20161202_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('N', 'New'), ('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running'), ('O', 'Store Job Output'), ('T', 'Terminate VM'), ('F', 'Finished'), ('E', 'Errored'), ('C', 'Canceled')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_errors', to='data.Job')),
            ],
        ),
    ]
