# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_joberror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DDSApplicationCredential',
            new_name='DDSEndpoint',
        ),
        migrations.RemoveField(
            model_name='ddsjobinputfile',
            name='dds_app_credentials',
        ),
        migrations.RemoveField(
            model_name='joboutputdir',
            name='dds_app_credentials',
        ),
        migrations.AddField(
            model_name='ddsusercredential',
            name='endpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.DDSEndpoint'),
            preserve_default=False,
        ),
    ]
