# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161207_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('queue_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running'), ('O', 'Store Job Output'), ('T', 'Terminate VM'), ('F', 'Finished'), ('E', 'Error'), ('C', 'Canceled')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='joberror',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running'), ('O', 'Store Job Output'), ('T', 'Terminate VM'), ('F', 'Finished'), ('E', 'Error'), ('C', 'Canceled')], max_length=1),
        ),
    ]
