# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170524_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_flavor', models.CharField(help_text='The name of the flavor to use when launching instances (specifies CPU/RAM)', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VMProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_project_name', models.CharField(help_text='The name of the project in which to launch instances', max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='jobanswer',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='jobanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobddsfileanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='jobddsfileanswer',
            name='dds_user_credentials',
        ),
        migrations.RemoveField(
            model_name='jobddsoutputdirectoryanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='jobddsoutputdirectoryanswer',
            name='dds_user_credentials',
        ),
        migrations.RemoveField(
            model_name='jobstringanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='jobanswerset',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='jobquestionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='user_job_order',
            field=models.TextField(help_text='JSON containing the portion of the job order specified by user', null=True),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='system_job_order',
            field=models.TextField(help_text='JSON containing the portion of the job order specified by system.', null=True),
        ),
        migrations.DeleteModel(
            name='JobAnswer',
        ),
        migrations.DeleteModel(
            name='JobDDSFileAnswer',
        ),
        migrations.DeleteModel(
            name='JobDDSOutputDirectoryAnswer',
        ),
        migrations.DeleteModel(
            name='JobQuestion',
        ),
        migrations.DeleteModel(
            name='JobStringAnswer',
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='vm_flavor',
            field=models.ForeignKey(default=0, help_text='VM Flavor to use when creating VM instances for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMFlavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='vm_project',
            field=models.ForeignKey(default=0, help_text='Project name to use when creating VM instances for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMProject'),
            preserve_default=False,
        ),
    ]
