# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170525_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanswerset',
            name='job_name',
            field=models.CharField(default='', help_text='Name of the job', max_length=255),
            preserve_default=False,
        ),
    ]
