# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-09 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0008_jobquestionnaire_user_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFileStageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobinputfile',
            name='job',
        ),
        migrations.RenameField(
            model_name='vmflavor',
            old_name='vm_flavor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vmproject',
            old_name='vm_project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ddsjobinputfile',
            name='index',
        ),
        migrations.RemoveField(
            model_name='ddsjobinputfile',
            name='job_input_file',
        ),
        migrations.RemoveField(
            model_name='urljobinputfile',
            name='index',
        ),
        migrations.RemoveField(
            model_name='urljobinputfile',
            name='job_input_file',
        ),
        migrations.AlterField(
            model_name='urljobinputfile',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='JobInputFile',
        ),
        migrations.AddField(
            model_name='ddsjobinputfile',
            name='stage_group',
            field=models.ForeignKey(default=0, help_text='Stage group to which this file belongs', on_delete=django.db.models.deletion.CASCADE, related_name='dds_files', to='data.JobFileStageGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='stage_group',
            field=models.OneToOneField(help_text='Group of files to stage when running this job', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobFileStageGroup'),
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='stage_group',
            field=models.OneToOneField(help_text='Collection of files that must be staged for a job to be run', null=-1, on_delete=django.db.models.deletion.CASCADE, to='data.JobFileStageGroup'),
        ),
        migrations.AddField(
            model_name='urljobinputfile',
            name='stage_group',
            field=models.ForeignKey(default=0, help_text='Stage group to which this file belongs', on_delete=django.db.models.deletion.CASCADE, related_name='url_files', to='data.JobFileStageGroup'),
            preserve_default=False,
        ),
    ]
