# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20161207_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vm_instance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
