# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170605_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboutputproject',
            name='dir_name',
        ),
    ]
