# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-13 20:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170609_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanswerset',
            name='stage_group',
            field=models.OneToOneField(help_text='Collection of files that must be staged for a job to be run', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobFileStageGroup'),
        ),
    ]
