# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170613_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobanswerset',
            old_name='user_job_order',
            new_name='user_job_order_json',
        ),
    ]
