# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_job_vm_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vm_flavor',
            field=models.CharField(default='m1.small', help_text='Determines CPUs and RAM VM allocation used to run this job.', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_instance_name',
            field=models.CharField(blank=True, help_text='Name of the vm this job is/was running on.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_project_name',
            field=models.CharField(default='jpb67', help_text='Name of the cloud project where vm will be created.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='workflow_input_json',
            field=models.TextField(help_text='CWL input json for use with the workflow.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='object_name',
            field=models.CharField(default='#main', help_text="Name of the object in a packed workflow to run. Typically set to '#main'.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='url',
            field=models.URLField(help_text='URL to packed CWL workflow file.'),
        ),
    ]
