# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20161213_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversion',
            name='url',
            field=models.URLField(help_text='URL to packed CWL workflow file.'),
        ),
    ]
