# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20170614_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='user_fields',
            new_name='user_fields_json',
        ),
    ]
