# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0014_auto_20161213_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ddsusercredential',
            unique_together=set([('endpoint', 'user')]),
        ),
    ]
