# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20161213_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='step',
            field=models.CharField(choices=[('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running Workflow'), ('O', 'Store Job Output'), ('T', 'Terminate VM')], help_text='Job step (progress within Running state)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('C', 'Canceled')], default='N', help_text='High level state of the project', max_length=1),
        ),
        migrations.AlterField(
            model_name='joberror',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('C', 'Canceled')], max_length=1),
        ),
    ]
