# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20170706_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='step',
            field=models.CharField(blank=True, choices=[('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running Workflow'), ('O', 'Store Job Output'), ('T', 'Terminate VM')], help_text='Job step (progress within Running state)', max_length=1, null=True),
        ),
    ]
