# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 15:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20170706_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='run_token',
            field=models.OneToOneField(blank=True, help_text='Token that allows permission for a job to be run', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobToken'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Authorized'), ('S', 'Starting'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('c', 'Canceling'), ('C', 'Canceled'), ('r', 'Restarting')], default='N', help_text='High level state of the project', max_length=1),
        ),
    ]
