# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20161214_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joberror',
            old_name='job_stage',
            new_name='job_step',
        ),
    ]
