# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20170706_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='volume_size',
            field=models.IntegerField(default=100, help_text='Size in GB of volume created for running this job'),
            preserve_default=False,
        ),
    ]
