# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20161214_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
