# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 13:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_job_volume_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_size',
            field=models.IntegerField(default=100, help_text='Size in GB of volume created for running this job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='volume_size',
            field=models.IntegerField(default=100, help_text='Size in GB of volume created for running this job'),
        ),
    ]
