# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_workflowversion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='', help_text='User specified name for this job.', max_length=255),
            preserve_default=False,
        ),
    ]
