# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversion',
            name='version',
            field=models.IntegerField(),
        ),
    ]
