# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0021_auto_20161222_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, help_text='Used to order array answers', null=True)),
                ('kind', models.CharField(choices=[('string', 'DukeDS File'), ('dds_file', 'Text')], help_text='Determines child table associated with this answer.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Name to be used in CWL workflow.', max_length=255)),
                ('name', models.CharField(help_text='User facing question text.', max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('File', 'File')], help_text='Determines how answer is formatted in CWL input json.', max_length=30)),
                ('occurs', models.IntegerField(default=1, help_text='If > 1 this is an array in the CWL input json')),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='User facing description', max_length=255)),
                ('questions', models.ManyToManyField(help_text='Questions that are required to create a job', to='data.JobQuestion')),
                ('workflow_version', models.ForeignKey(help_text='Workflow that this questionaire is for', on_delete=django.db.models.deletion.CASCADE, to='data.WorkflowVersion')),
            ],
        ),
        migrations.CreateModel(
            name='JobDDSFileAnswer',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dds_file', serialize=False, to='data.JobAnswer')),
                ('project_id', models.CharField(help_text='uuid from DukeDS for the project containing our file', max_length=255, null=True)),
                ('file_id', models.CharField(help_text='uuid from DukeDS for the file chosen as this answer', max_length=255, null=True)),
                ('dds_user_credentials', models.ForeignKey(help_text='Credentials with access to this file', on_delete=django.db.models.deletion.CASCADE, to='data.DDSUserCredential')),
            ],
        ),
        migrations.CreateModel(
            name='JobStringAnswer',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='string_value', serialize=False, to='data.JobAnswer')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='answers',
            field=models.ManyToManyField(help_text='User editable answers tied to this answer set', to='data.JobAnswer'),
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='questionnaire',
            field=models.ForeignKey(help_text='determines which questions are appropriate for this answer set', on_delete=django.db.models.deletion.CASCADE, to='data.JobQuestionnaire'),
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='user',
            field=models.ForeignKey(help_text='User who owns this answer set', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='data.JobQuestion'),
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='questionnaire',
            field=models.ForeignKey(blank=True, help_text='When null this is a user editable answer otherwise it is a system answer', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobQuestionnaire'),
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='user',
            field=models.ForeignKey(help_text='User who created this job answer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
