# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20170113_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobddsfileanswer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobstringanswer',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobddsfileanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dds_file', to='data.JobAnswer'),
        ),
        migrations.AlterField(
            model_name='jobstringanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='string_value', to='data.JobAnswer'),
        ),
    ]
