# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20170117_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanswer',
            name='kind',
            field=models.CharField(choices=[('dds_file', 'DukeDS File'), ('string', 'Text')], help_text='Determines child table associated with this answer.', max_length=30),
        ),
    ]
