# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 19:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20170801_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vm_volume_name',
            field=models.CharField(blank=True, help_text='Name of the volume attached to store data for this job.', max_length=255, null=True),
        ),
    ]
