# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20170120_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanswer',
            name='kind',
            field=models.CharField(choices=[('string', 'Text'), ('dds_file', 'DukeDS File')], help_text='Determines child table associated with this answer.', max_length=30),
        ),
    ]
