# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20170118_1946'),
        ('data', '0025_auto_20170120_2046'),
    ]

    operations = [
    ]
