# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_merge_20170120_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanswer',
            name='kind',
            field=models.CharField(choices=[('string', 'Text'), ('dds_file', 'DukeDS File')], help_text='Determines child table associated with this answer.', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobquestion',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('File', 'File'), ('Directory', 'Directory')], help_text='Determines how answer is formatted in CWL input json.', max_length=30),
        ),
    ]
