# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20170817_1716'),
    ]

    operations = [
        migrations.RenameField('JobQuestionnaire', 'volume_size', 'volume_size_base'),
    ]
