# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_job_fund_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionnaire',
            name='fund_code',
            field=models.CharField(blank=True, help_text='Fund code this job will be charged to.', max_length=255, null=True),
        ),
    ]
