# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20170913_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsjobinputfile',
            name='size',
            field=models.IntegerField(default=0, help_text='Size of file in bytes'),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_size_factor',
            field=models.IntegerField(default=0, help_text='Number multiplied by total staged data size for determining job volume size'),
        ),
        migrations.AddField(
            model_name='urljobinputfile',
            name='size',
            field=models.IntegerField(default=0, help_text='Size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='volume_size_base',
            field=models.IntegerField(default=100, help_text='Base size in GB of for determining job volume size'),
        ),
    ]
