# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20170913_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsjobinputfile',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='urljobinputfile',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Size of file in bytes'),
        ),
    ]
