# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20170913_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowMethodsDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Methods document contents.')),
                ('filename', models.CharField(help_text='Filename to save the methods document into.', max_length=255)),
                ('workflow_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='methods_document', to='data.WorkflowVersion')),
            ],
        ),
    ]
