# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 18:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20170914_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharegroup',
            name='email',
            field=models.EmailField(help_text='Contact email for this group', max_length=254, null=True),
        ),
    ]
