# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_workflowmethodsdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowmethodsdocument',
            name='filename',
        ),
        migrations.AlterField(
            model_name='workflowmethodsdocument',
            name='content',
            field=models.TextField(help_text='Methods document contents in markdown.'),
        ),
    ]
