# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20170122_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='workflow_input_json',
            new_name='job_order',
        ),
    ]
