# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20170209_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionnaire',
            name='name',
            field=models.CharField(default='', help_text='Short user facing name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='description',
            field=models.TextField(help_text='Detailed user facing description'),
        ),
    ]
