# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 18:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20170921_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Text of the message body')),
                ('subject', models.TextField(verbose_name='Text of the message subject')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Email address of the sender')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email address of the recipient')),
                ('state', models.TextField(choices=[('N', 'New'), ('S', 'Sent'), ('E', 'Error')], default='N')),
                ('errors', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the template', max_length=255, unique=True)),
                ('body_template', models.TextField(help_text='Template text for the message body')),
                ('subject_template', models.TextField(help_text='Template text for the message subject')),
            ],
        ),
    ]
