# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-10 14:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20170929_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboutputdir',
            name='readme_file_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
