# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_joboutputdir_readme_file_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOutputDir',
            new_name='JobDDSOutputProject'
        ),
        migrations.RemoveField(
            model_name='jobddsoutputproject',
            name='dir_name',
        ),
    ]
