# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-06 16:23


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_rename_joboutputdir_20171013_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Authorized'), ('S', 'Starting'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('c', 'Canceling'), ('C', 'Canceled'), ('r', 'Restarting'), ('D', 'Deleted')], default='N', help_text='High level state of the project', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobddsoutputproject',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_project', to='data.Job'),
        ),
    ]
