# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20171208_1842_2'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='jobquestionnaire',
            name='vm_project',
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_mounts',
            field=models.TextField(default=b'{"/dev/vdb1": "/work"}',
                                   help_text='JSON-encoded list of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),

        # Remove the default value
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='vm_settings',
            field=models.ForeignKey(
                help_text='Collection of settings to use when launching job VMs for this questionnaire',
                on_delete=django.db.models.deletion.CASCADE, to='data.VMSettings'),
        ),

        #############################
        # Update Jobs
        #############################
        migrations.RenameField(
            model_name='job',
            old_name='vm_flavor',
            new_name='vm_flavor_name'
        ),
        migrations.AddField(
            model_name='job',
            name='vm_flavor',
            field=models.ForeignKey(help_text='VM Flavor to use when creating VM instances for this questionnaire',
                                    on_delete=django.db.models.deletion.CASCADE, to='data.VMFlavor'),
        ),
        migrations.AddField(
            model_name='job',
            name='vm_settings',
            field=models.ForeignKey(default=0, help_text='Collection of settings to use when launching VM for this job',
                                    on_delete=django.db.models.deletion.CASCADE, to='data.VMSettings'),
            preserve_default=False,
        ),

    ]
