# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20171106_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_settings', help_text='Short name of this cloudsettings', max_length=255, unique=True)),
                ('ssh_key_name', models.CharField(help_text='Name of SSH key to inject into VM on launch', max_length=255)),
                ('network_name', models.CharField(help_text='Name of network to attach VM to on launch', max_length=255)),
                ('allocate_floating_ips', models.BooleanField(default=False, help_text='Allocate floating IPs to launched VMs')),
                ('floating_ip_pool_name', models.CharField(blank=True, help_text='Name of floating IP pool to allocate from', max_length=255, null=True)),
                ('vm_project', models.ForeignKey(help_text='Project name to use when creating VM instances for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMProject')),
            ],
        ),
        migrations.CreateModel(
            name='VMSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_settings', help_text='Short name of these settings', max_length=255, unique=True)),
                ('image_name', models.CharField(help_text='Name of the VM Image to launch', max_length=255)),
                ('cwl_base_command', models.TextField(help_text="JSON-encoded command array to run the  image's installed CWL engine")),
                ('cwl_post_process_command', models.TextField(blank=True, help_text='JSON-encoded command array to run after workflow completes', null=True)),
                ('cwl_pre_process_command', models.TextField(blank=True, help_text='JSON-encoded command array to run before cwl_base_command', null=True)),
                ('cloud_settings', models.ForeignKey(help_text='Cloud settings ', on_delete=django.db.models.deletion.CASCADE, to='data.CloudSettings')),
            ],
            options={
                'verbose_name_plural': 'VM Settings Collections',
            },
        ),
        #############################
        # Update JobQuestionnaires
        #############################
        # Add JobQuestionnaire.vm_settings, initially allowing nulls
        migrations.AddField(
            model_name='jobquestionnaire',
            name='vm_settings',
            field=models.ForeignKey(null=True, help_text='Collection of settings to use when launching job VMs for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMSettings'),
            preserve_default=False,
        ),
    ]
