# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 18:42


from django.db import migrations, models
import django.db.models.deletion


def update_jobs(apps, schema_editor):
    """
    In this migration, we update jobs so that
    1. CharField vm_flavor_name is normalized into a VMFlavor foreign key
    2. CharField vm_project_name is normalized into a VMProject foreign key, and referenced via
        Job -> VMSettings -> CloudSettings -> VMProject
    """
    Job = apps.get_model("data", "Job")
    VMSettings = apps.get_model("data", "VMSettings")
    VMProject = apps.get_model("data", "VMProject")
    CloudSettings = apps.get_model("data", "CloudSettings")
    VMFlavor = apps.get_model("data", "VMFlavor")
    for j in Job.objects.all():
        # 1. handle vm_flavor
        vm_flavor, _ = VMFlavor.objects.get_or_create(name=j.vm_flavor_name)
        j.vm_flavor = vm_flavor

        # 2. Handle vm_project
        vm_project, _ = VMProject.objects.get_or_create(name=j.vm_project_name)
        cloud_settings, _ = CloudSettings.objects.get_or_create(name=j.vm_project_name, vm_project=vm_project)
        vm_settings, _ = VMSettings.objects.get_or_create(name=vm_project.name, cloud_settings=cloud_settings)
        j.vm_settings = vm_settings
        j.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_3_schema_add_job_vmsettings_fields'),
    ]

    operations = [
        # Populate VMSettings and CloudSettings objects from Job
        migrations.RunPython(update_jobs),
    ]
