# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


def populate_sequence_fields(apps, schema_editor):
    populate_sequence_for_model(apps.get_model('data', 'DDSJobInputFile'))
    populate_sequence_for_model(apps.get_model('data', 'URLJobInputFile'))


def populate_sequence_for_model(model):
    for input_file in model.objects.all():
        input_file.sequence = input_file.id
        input_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20171106_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsjobinputfile',
            name='sequence',
            field=models.IntegerField(help_text='Determines order within the job', null=True),
        ),
        migrations.AddField(
            model_name='urljobinputfile',
            name='sequence',
            field=models.IntegerField(help_text='Determines order within the job', null=True),
        ),
        migrations.RunPython(populate_sequence_fields),
    ]
