# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-11 19:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_5_schema_remove_job_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='volume_mounts',
            field=models.TextField(default=b'{"/dev/vdb1": "/work"}', help_text='JSON-encoded dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='volume_mounts',
            field=models.TextField(default=b'{"/dev/vdb1": "/work"}', help_text='JSON-encoded dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
    ]
