# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-11 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_add_input_file_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ddsjobinputfile',
            unique_together=set([('stage_group', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='urljobinputfile',
            unique_together=set([('stage_group', 'sequence')]),
        ),
    ]
