# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20171205_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmsettings',
            name='cwl_pre_process_command',
            field=models.TextField(blank=True, help_text='JSON-encoded command array to run before cwl_base_command', null=True),
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_base_command',
            field=models.TextField(help_text="JSON-encoded command array to run the  image's installed CWL engine"),
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_post_process_command',
            field=models.TextField(blank=True, help_text='JSON-encoded command arrayto run after workflow completes', null=True),
        ),
    ]
