# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20171206_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vm_flavor',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vm_project_name',
        ),
        migrations.AddField(
            model_name='job',
            name='vm_settings',
            field=models.ForeignKey(default=0, help_text='Collection of settings to use when launching VM for this job', on_delete=django.db.models.deletion.CASCADE, to='data.VMSettings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_post_process_command',
            field=models.TextField(blank=True, help_text='JSON-encoded command array to run after workflow completes', null=True),
        ),
    ]
