# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-12 21:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20171212_1856'),
        ('data', '0039_add_input_file_sequences'),
    ]

    operations = [
    ]
