# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20171207_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmsettings',
            name='name',
            field=models.CharField(default='default_settings', help_text='Short name of these settings', max_length=255, unique=True),
        ),
    ]
