# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_vmsettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmsettings',
            name='volume_size_base',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='volume_size_factor',
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_size_base',
            field=models.IntegerField(default=100, help_text='Base size in GB of for determining job volume size'),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_size_factor',
            field=models.IntegerField(default=0, help_text='Number multiplied by total staged data size for determining job volume size'),
        ),
    ]
