# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 18:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_merge_20171212_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudsettings',
            options={'verbose_name_plural': 'Cloud Settings Collections'},
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_flavor',
            field=models.ForeignKey(help_text='VM Flavor to use when launching VM for this job', on_delete=django.db.models.deletion.CASCADE, to='data.VMFlavor'),
        ),
    ]
