# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20171208_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_settings', help_text='Short name of this cloudsettings', max_length=255, unique=True)),
                ('ssh_key_name', models.CharField(help_text='Name of SSH key to inject into VM on launch', max_length=255)),
                ('network_name', models.CharField(help_text='Name of network to attach VM to on launch', max_length=255)),
                ('allocate_floating_ips', models.BooleanField(default=False, help_text='Allocate floating IPs to launched VMs')),
                ('floating_ip_pool_name', models.CharField(blank=True, help_text='Name of floating IP pool to allocate from', max_length=255, null=True)),
                ('vm_project', models.ForeignKey(help_text='Project name to use when creating VM instances for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMProject')),
            ],
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='allocate_floating_ips',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='floating_ip_pool_name',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='network_name',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='ssh_key_name',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='vm_flavor',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='vm_project',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='volume_mounts',
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='vm_flavor',
            field=models.ForeignKey(default=0, help_text='VM Flavor to use when creating VM instances for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.VMFlavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_mounts',
            field=models.TextField(default=b'{"/dev/vdb1": "/work"}', help_text='JSON-encoded list of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
        migrations.AddField(
            model_name='vmsettings',
            name='cloud_settings',
            field=models.ForeignKey(default=0, help_text='Cloud settings ', on_delete=django.db.models.deletion.CASCADE, to='data.CloudSettings'),
            preserve_default=False,
        ),
    ]
