# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-19 19:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20171214_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('N', 'New'), ('A', 'Authorized'), ('S', 'Starting'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('c', 'Canceling'), ('C', 'Canceled'), ('r', 'Restarting'), ('D', 'Deleted')], default='N', help_text='High level state of the project', max_length=1)),
                ('step', models.CharField(blank=True, choices=[('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running Workflow'), ('O', 'Store Job Output'), ('T', 'Terminate VM')], help_text='Job step (progress within Running state)', max_length=1, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_activities', to='data.Job')),
            ],
        ),
    ]
