# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-16 16:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_jobactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobactivity',
            options={'verbose_name_plural': 'Job Activities'},
        ),
    ]
