# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_jobactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobactivity',
            options={'verbose_name_plural': 'Job Activities'},
        ),
        migrations.AddField(
            model_name='cloudsettings',
            name='max_volume_size',
            field=models.IntegerField(default=16000, help_text='Max volume size in GB supported by this cloud'),
        ),
    ]
