# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-18 20:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20180116_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudsettings',
            name='floating_ip_pool_name',
            field=models.CharField(blank=True, default='', help_text='Name of floating IP pool to allocate from', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ddsjobinputfile',
            name='destination_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ddsjobinputfile',
            name='file_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ddsjobinputfile',
            name='project_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='bcc_email',
            field=models.TextField(blank=True, default='', help_text='space-separated Email addresses to bcc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='errors',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='fund_code',
            field=models.CharField(blank=True, default='', help_text='Fund code this job will be charged to.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_order',
            field=models.TextField(blank=True, default='', help_text='CWL input json for use with the workflow.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='run_token',
            field=models.OneToOneField(blank=True, default='', help_text='Token that allows permission for a job to be run', on_delete=django.db.models.deletion.CASCADE, to='data.JobToken'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='step',
            field=models.CharField(blank=True, choices=[('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running Workflow'), ('O', 'Store Job Output'), ('T', 'Terminate VM')], default='', help_text='Job step (progress within Running state)', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_instance_name',
            field=models.CharField(blank=True, default='', help_text='Name of the vm this job is/was running on.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_volume_name',
            field=models.CharField(blank=True, default='', help_text='Name of the volume attached to store data for this job.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='step',
            field=models.CharField(blank=True, choices=[('V', 'Create VM'), ('S', 'Staging In'), ('R', 'Running Workflow'), ('O', 'Store Job Output'), ('T', 'Terminate VM')], default='', help_text='Job step (progress within Running state)', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobanswerset',
            name='fund_code',
            field=models.CharField(blank=True, default='', help_text='Fund code this job will be charged to.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobanswerset',
            name='stage_group',
            field=models.OneToOneField(blank=True, help_text='Collection of files that must be staged for a job to be run', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobFileStageGroup'),
        ),
        migrations.AlterField(
            model_name='jobanswerset',
            name='user_job_order_json',
            field=models.TextField(blank=True, default=b'{}', help_text='JSON containing the portion of the job order specified by user'),
        ),
        migrations.AlterField(
            model_name='jobddsoutputproject',
            name='dds_user_credentials',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.DDSUserCredential'),
        ),
        migrations.AlterField(
            model_name='jobddsoutputproject',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobddsoutputproject',
            name='readme_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='system_job_order_json',
            field=models.TextField(blank=True, default='', help_text='JSON containing the portion of the job order specified by system.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='user_fields_json',
            field=models.TextField(blank=True, default='', help_text='JSON containing the array of fields required by the user when providing a job answer set.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Contact email for this group', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urljobinputfile',
            name='destination_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urljobinputfile',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_post_process_command',
            field=models.TextField(blank=True, default='', help_text='JSON-encoded command array to run after workflow completes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_pre_process_command',
            field=models.TextField(blank=True, default='', help_text='JSON-encoded command array to run before cwl_base_command'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='object_name',
            field=models.CharField(blank=True, default='#main', help_text="Name of the object in a packed workflow to run. Typically set to '#main'.", max_length=255),
        ),
    ]
