# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20180419_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='slug',
            field=models.CharField(help_text='Unique slug to represent this workflow', max_length=255, null=True, unique=True),
        ),
    ]
