# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-06 20:33
from __future__ import unicode_literals

from django.db import migrations


def populate_workflow_slugs(apps, schema_editor):
    Workflow = apps.get_model("data", "Workflow")
    for workflow in Workflow.objects.all():
        slug = '{}_{}'.format(workflow.name.replace(' ', '_'), workflow.id)
        workflow.slug = slug
        workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_workflow_slug'),
    ]

    operations = [
        migrations.RunPython(populate_workflow_slugs, migrations.RunPython.noop),
    ]
