# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-11 20:00
from __future__ import unicode_literals

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20180611_1534'),
    ]

    operations = [
    ]
