# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-15 15:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20180612_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobquestionnairetype',
            old_name='slug',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='slug',
            new_name='tag',
        ),
    ]
