# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20180606_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestionnaireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique slug for specifying a questionnaire for a workflow version', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.SlugField(help_text='Unique slug to represent this workflow', unique=True),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='type',
            field=models.ForeignKey(help_text='Type of questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.JobQuestionnaireType'),
        ),
    ]
