# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-15 17:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20180614_1917'),
        ('data', '0050_auto_20180612_1415'),
    ]

    operations = [
    ]
