# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_auto_20180615_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestionnairetype',
            name='tag',
            field=models.SlugField(help_text='Unique tag for specifying a questionnaire for a workflow version', unique=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='tag',
            field=models.SlugField(help_text='Unique tag to represent this workflow', unique=True),
        ),
    ]
