# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-15 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_merge_20180615_1758'),
        ('data', '0052_auto_20180615_1537'),
    ]

    operations = [
    ]
