# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_merge_20180615_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmflavor',
            name='cpus',
            field=models.IntegerField(default=1, help_text='How many CPUs are assigned to this flavor'),
        ),
    ]
