# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-01 15:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_auto_20181101_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vm_volume_mounts_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}', null=True),
        ),
        migrations.AddField(
            model_name='jobanswerset',
            name='user_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Dictionary of the job order specified by user', null=True),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='system_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Dictionary portion of the job order specified by system.', null=True),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='user_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Array of fields required by the user when providing a job answer set.', null=True),
        ),
        migrations.AddField(
            model_name='jobquestionnaire',
            name='volume_mounts_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}', null=True),
        ),
        migrations.AddField(
            model_name='vmsettings',
            name='cwl_base_command_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Command array to run the  image's installed CWL engine", null=True),
        ),
        migrations.AddField(
            model_name='vmsettings',
            name='cwl_post_process_command_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Command array to run after workflow completes', null=True),
        ),
        migrations.AddField(
            model_name='vmsettings',
            name='cwl_pre_process_command_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Command array to run before cwl_base_command', null=True),
        ),
        migrations.AddField(
            model_name='vmstrategy',
            name='volume_mounts_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}', null=True),
        ),
        migrations.AddField(
            model_name='workflowconfiguration',
            name='system_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Dictionary containing the portion of the job order specified by system.', null=True),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Array of fields required by this workflow.', null=True),
        ),
    ]
