# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-01 15:17
from __future__ import unicode_literals

from django.db import migrations
import json


def populate_json_fields(apps, schema_editor):
    converting_fields = [
        # class              source field   destination field
        ("WorkflowVersion", "fields_json", "fields"),
        ("VMSettings", "cwl_base_command", "cwl_base_command_new"),
        ("VMSettings", "cwl_post_process_command", "cwl_post_process_command_new"),
        ("VMSettings", "cwl_pre_process_command", "cwl_pre_process_command_new"),
        ("Job", "vm_volume_mounts", "vm_volume_mounts_new"),
        ("JobQuestionnaire", "system_job_order_json", "system_job_order"),
        ("JobQuestionnaire", "user_fields_json", "user_fields"),
        ("JobQuestionnaire", "volume_mounts", "volume_mounts_new"),
        ("JobAnswerSet", "user_job_order_json", "user_job_order"),
        ("VMStrategy", "volume_mounts", "volume_mounts_new"),
        ("WorkflowConfiguration", "system_job_order_json", "system_job_order"),
    ]
    for converting_field in converting_fields:
        class_name, source_field, dest_field = converting_field
        Model = apps.get_model("data", class_name)
        for obj in Model.objects.all():
            json_str = getattr(obj, source_field)
            try:
                setattr(obj, dest_field, json.loads(json_str))
                obj.save()
            except json.decoder.JSONDecodeError:
                x = 1


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_auto_20181101_1557'),
    ]

    operations = [
        migrations.RunPython(populate_json_fields, migrations.RunPython.noop),
    ]
