# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-01 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_populate_json_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vm_volume_mounts',
        ),
        migrations.RemoveField(
            model_name='jobanswerset',
            name='user_job_order_json',
        ),
        migrations.RemoveField(
            model_name='jobquestionnaire',
            name='system_job_order_json',
        ),
        migrations.RemoveField(
            model_name='jobquestionnaire',
            name='user_fields_json',
        ),
        migrations.RemoveField(
            model_name='jobquestionnaire',
            name='volume_mounts',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='cwl_base_command',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='cwl_post_process_command',
        ),
        migrations.RemoveField(
            model_name='vmsettings',
            name='cwl_pre_process_command',
        ),
        migrations.RemoveField(
            model_name='vmstrategy',
            name='volume_mounts',
        ),
        migrations.RemoveField(
            model_name='workflowconfiguration',
            name='system_job_order_json',
        ),
        migrations.RemoveField(
            model_name='workflowversion',
            name='fields_json',
        ),
    ]
