# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-01 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_remove_old_json_text_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vm_volume_mounts_new',
            new_name='vm_volume_mounts',
        ),
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='volume_mounts_new',
            new_name='volume_mounts',
        ),
        migrations.RenameField(
            model_name='vmsettings',
            old_name='cwl_base_command_new',
            new_name='cwl_base_command',
        ),
        migrations.RenameField(
            model_name='vmsettings',
            old_name='cwl_post_process_command_new',
            new_name='cwl_post_process_command',
        ),
        migrations.RenameField(
            model_name='vmsettings',
            old_name='cwl_pre_process_command_new',
            new_name='cwl_pre_process_command',
        ),
        migrations.RenameField(
            model_name='vmstrategy',
            old_name='volume_mounts_new',
            new_name='volume_mounts',
        ),
    ]
