# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_remove_json_field_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowconfiguration',
            name='system_job_order_json',
        ),
        migrations.RemoveField(
            model_name='workflowversion',
            name='fields_json',
        ),
    ]
