# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-01 19:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_rename_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vm_volume_mounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
        migrations.AlterField(
            model_name='jobanswerset',
            name='user_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Dictionary of the job order specified by user'),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='system_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Dictionary portion of the job order specified by system.'),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='user_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Array of fields required by the user when providing a job answer set.'),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='volume_mounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_base_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Command array to run the  image's installed CWL engine"),
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_post_process_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Command array to run after workflow completes'),
        ),
        migrations.AlterField(
            model_name='vmsettings',
            name='cwl_pre_process_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Command array to run before cwl_base_command'),
        ),
        migrations.AlterField(
            model_name='vmstrategy',
            name='volume_mounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'/dev/vdb1': '/work'}, help_text='Dictionary of volume mounts, e.g. {"/dev/vdb1": "/work"}'),
        ),
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='system_job_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Dictionary containing the portion of the job order specified by system.'),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Array of fields required by this workflow.'),
        ),
    ]
