# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_remove_old_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowconfiguration',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Workflow'),
        ),
    ]
