# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-14 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_populate_config_workflow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowconfiguration',
            unique_together=set([('workflow', 'name')]),
        ),
    ]
