# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-14 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_update_workflow_config_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowconfiguration',
            name='workflow_version',
        ),
    ]
