# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_remove_workflowconfiguration_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Workflow'),
        ),
    ]
