# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_remove_workflow_configuration_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowconfiguration',
            name='tag',
            field=models.SlugField(help_text='Unique tag to represent this workflow', null=True, unique=True),
        ),
    ]
