# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-29 17:20
from __future__ import unicode_literals

from django.db import migrations


def populate_workflow_configuration_tag(apps, schema_editor):
    WorkflowConfiguration = apps.get_model("data", "WorkflowConfiguration")
    for obj in WorkflowConfiguration.objects.all():
        obj.tag = obj.name
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_workflowconfiguration_tag'),
    ]

    operations = [
        migrations.RunPython(populate_workflow_configuration_tag, migrations.RunPython.noop),
    ]
