# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-29 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_auto_20181129_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowconfiguration',
            name='name',
        ),
    ]
