# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_remove_workflowconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='tag',
            field=models.SlugField(help_text='Unique tag to represent this workflow'),
        ),
    ]
