# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_auto_20181129_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='workflow_version',
            field=models.ForeignKey(help_text=b'Workflow that this questionaire is for', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='data.WorkflowVersion'),
        ),
    ]
