# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_auto_20181210_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='enable_ui',
            field=models.BooleanField(default=True, help_text=b'Should this workflow version be selectable via the web portal.'),
        ),
    ]
