"""
Django settings for bespin project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from bespin.settings_base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+u!*o@^1!elg34r5u$z4xgq(_yq@fqw!d^4p6y*zh_o1buifsa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# So that pages served by ember development server are listed as OK to access this API
CORS_ORIGIN_WHITELIST = (
    'localhost:4200',
    '127.0.0.1:4200',
)

DEFAULT_FROM_EMAIL = 'gcb-bespin@duke.edu'
BESPIN_MAILER_ADMIN_BCC = []
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
